In [1]:
import numpy as np

In [2]:
a = np.random.randn(2, 3) # a.shape = (2, 3)
b = np.random.randn(2, 1) # b.shape = (2, 1)
c = a + b

In [3]:
c.shape

(2, 3)

In [9]:
a = np.random.randn(4, 3) # a.shape = (4, 3)
b = np.random.randn(3, 2) # b.shape = (3, 2)
c = a*b # element-wise multiplication

ValueError: operands could not be broadcast together with shapes (4,3) (3,2) 

In [ ]:
c.shape

In [5]:
a = np.random.randn(12288, 150) # a.shape = (12288, 150)
b = np.random.randn(150, 45) # b.shape = (150, 45)
c = np.dot(a,b) # matrix multiplication

In [6]:
c.shape

(12288, 45)

In [15]:
a = np.random.randn(3, 4) # a.shape = (3,4)
b = np.random.randn(4, 1) # b.shape = (4,1)
c = np.zeros((3, 4))

for i in range(3):
    for j in range(4):
        c[i][j] = a[i][j] + b[j]

In [16]:
c

array([[ 1.04758157,  1.33651005, -2.99086258,  1.14943568],
       [-0.2667697 ,  0.95773408, -2.29032569,  3.43712883],
       [-0.92393754, -1.05360847, -2.06984406,  1.39393074]])

In [18]:
a + np.transpose(b)

array([[ 1.04758157,  1.33651005, -2.99086258,  1.14943568],
       [-0.2667697 ,  0.95773408, -2.29032569,  3.43712883],
       [-0.92393754, -1.05360847, -2.06984406,  1.39393074]])

In [19]:
a = np.random.randn(3, 3)
b = np.random.randn(3, 1)
c = a*b

In [20]:
c

array([[-0.01098458, -0.0064687 ,  0.03882929],
       [-0.91509331,  0.54132166, -0.13545573],
       [-0.41427009,  0.12700517, -1.2458701 ]])